/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BakicilarRouteImport } from './routes/bakicilar'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as KayitRouteImport } from './routes/kayit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BakicilarRoute = BakicilarRouteImport.update({
  id: '/bakicilar',
  path: '/bakicilar',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitRoute = KayitRouteImport.update({
  id: '/kayit',
  path: '/kayit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bakicilar': typeof BakicilarRoute
  '/giris': typeof GirisRoute
  '/kayit': typeof KayitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bakicilar': typeof BakicilarRoute
  '/giris': typeof GirisRoute
  '/kayit': typeof KayitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bakicilar': typeof BakicilarRoute
  '/giris': typeof GirisRoute
  '/kayit': typeof KayitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bakicilar' | '/giris' | '/kayit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bakicilar' | '/giris' | '/kayit'
  id: '__root__' | '/' | '/bakicilar' | '/giris' | '/kayit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BakicilarRoute: typeof BakicilarRoute
  GirisRoute: typeof GirisRoute
  KayitRoute: typeof KayitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakicilar': {
      id: '/bakicilar'
      path: '/bakicilar'
      fullPath: '/bakicilar'
      preLoaderRoute: typeof BakicilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit': {
      id: '/kayit'
      path: '/kayit'
      fullPath: '/kayit'
      preLoaderRoute: typeof KayitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BakicilarRoute: BakicilarRoute,
  GirisRoute: GirisRoute,
  KayitRoute: KayitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
